### ISSUE TITLE
Doesn't handle a flush of rules

### ISSUE THREAD

**Issue by kevinpascoe** [wk8/cookbook-diptables#4]
If someone was to run iptables -F on the box, then the next time the chef client runs, the firewall rules are not re-applied.

Is it possible to have the iptables-restore command run every time the chef client is run, thereby keeping the system in a known state?

**Comment by kevinpascoe** [comment]
Just saw the previous issue having the same problem. You offered to add a ['diptables']['force-reload'] node option. Would it be possible to implement this?

**Comment by wk8** [comment]
Fixed in version 1.0.1: https://github.com/wk8/cookbook-diptables/commit/873194b4bd1483e88174bb85302929ed07083bca
Please read the comments in that patch though ;-)
