### ISSUE TITLE
Placeholders doesn't work

### ISSUE THREAD

**Issue by riverfall** [wk8/cookbook-diptables#5]
Hi,

In your manual there is a template;
Is string -s %<remote_ip>s is correct?

I need to insert node ip address to the string,

I use:

diptables_rule '5275' do
rule '-s <% remote_ip >s --proto tcp --dport 5275'
  placeholders({:remote_ip => node['ipaddress']})
end

and get:
    diptables_rule("5275") do
      action :add
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :diptables_rule
      cookbook_name "maxoptra_internal"
      recipe_name "iptables"
      rule ["-s <%remote_ip>s --proto tcp --dport 5275"]
      placeholders {:remote_ip=>"192.168.21.29"}
      table "filter"
      chain "INPUT"
    end

[2015-09-02T10:33:11+03:00] ERROR: diptables_rule[5275] (maxoptra_internal::iptables line 74) had an error: SystemExit: exit

**Comment by wk8** [comment]
Your syntax is incorrect, see the correct syntax from the README, or
```
irb(main):007:0> sprintf('-s %< remote_ip >s --proto tcp --dport 3306', {remote_ip: '8.8.8.8'})
KeyError: key< remote_ip > not found
	from (irb):7:in `sprintf'
	from (irb):7
	from /Users/wk/.rubies/2.2.2/bin/irb:11:in `<main>'
irb(main):008:0> sprintf('-s %<remote_ip>s --proto tcp --dport 5275', {remote_ip: '8.8.8.8'})
=> "-s 8.8.8.8 --proto tcp --dport 5275"
```

That being said, also as mentioned in the README, you'd be much better off using a `diptables_tcp_udp_rule` for that:
```
diptables_tcp_udp_rule '5275' do
  dport 5275
  source '192.168.21.29'
end
```

Using `diptables_rule`s should only be for more complicated rules.

Closing this issue, but please feel free to re-open if you encounter further problems.

**Comment by riverfall** [comment]
Thank you!
It is resolved

Correct code is:

diptables_tcp_udp_rule '5275' do
dport 5275
source "#{node['ipaddress']}"
end

**Comment by wk8** [comment]
You don't need the string interpolation here, just node['ipaddress'] should work :-)
